package com.abhi.enterprizeprojects.SpringBootMicroservicesForBreweries.breweries.models.V2;


public enum BeerStyleEnum {
	
	
	BROWN_ALE, 
	PALE_ALE, 
	INDIA_PALE_ALE, 
	BLONDE_ALE, 
	FARMHOUSE_ALE, 
	BELGIAN_ALE, 
	CREAM_ALE, 
	STOUT, 
	PORTER, 
	WHEAT_BEER, 
	PALE_LAGER, 
	AMBER_LAGER, 
	AMERICAN_LAGER, 
	VIENNA_LAGER, 
	PILSNER,
	DORTMUNDER,
	OKTOBERFEST, 
	BOCK, 
	MUNICH_DUNKEL, 
	JAPANESE_RICE_LAGER, 
	AMERICAN_SOUR, 
	LAMBIC, 
	KOLSCH, 
	CALIFORNIA_COMMON

}
